name: Workflow to test code for acceptance at main branch

on:
  pull_request:
    branches: [main]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java environment
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Package Installation
        run: mvn clean install -DskipTests
      - name: Running Tests
        run: mvn test